### ISSUE TITLE
Incorrect output URL when version is github.sha

### ISSUE THREAD

**Issue by ebeloded** [google-github-actions/deploy-appengine#166]
### TL;DR

When version input is specified as `${{github.sha}}`, the action outputs an incorrect URL.

**Expected behavior**

Normally, when providing a version for a service, the URL produced looks like this:

```
VERSION-dot-SERVICE-dot-PROJECT_ID.REGION_ID.r.appspot.com
```

**Observed behavior**

However, when I specified `${{ github.sha }}` for the version, the output URL comes out with `.` instead of `-dot-`, which doesn't work:

```
VERSION.SERVICE.PROJECT_ID.REGION_ID.r.appspot.com
```

NB: The version gets deployed correctly and I can visit it by using the correct URL (with `-dot-`s).

### Reproduction

**Action YAML**

```yaml
uses: google-github-actions/deploy-appengine@main
with:
  project_id: ${{ env.PROJECT_ID }}
  credentials: ${{ env.SERVICE_ACCOUNT_KEY }}
  deliverables: ${{ env.CONFIG_FILE }}
  promote: false
  version: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) ||  github.sha  }}
```
