### ISSUE TITLE
Error authenticating the Cloud SDK

### ISSUE THREAD

**Issue by abdonrd** [google-github-actions/deploy-appengine#175]
### TL;DR

Error authenticating the Cloud SDK after update to `google-github-actions/auth@v0.4.1`.

With just this:

<img width="573" alt="Screenshot 2021-12-07 at 18 24 46" src="https://user-images.githubusercontent.com/1007051/145077127-6032a0bd-1593-4f97-b5ea-ceb1aaa5b37c.png">

Output:

<img width="999" alt="Screenshot 2021-12-07 at 18 27 15" src="https://user-images.githubusercontent.com/1007051/145077254-0c2b8168-635f-4817-9d0b-7757b95b944d.png">

### Action YAML

```yaml
jobs:
  deploy-staging:
    name: Deploy (staging)

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - run: npm ci
      - run: NODE_ENV=staging npm run build

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          deliverables: server/app.staging.yaml
          version: staging
          promote: false
```
