### ISSUE TITLE
Error authenticating the Cloud SDK.

### ISSUE THREAD

**Issue by cl8dep** [google-github-actions/deploy-appengine#180]
### TL;DR

Deploy to App Engine action is not authenticated after use Google Cloud Auth Action, so the deployment is failing.

### Expected behavior

If I use Google Cloud Auth action before Deploy to App Engine action, this must use the credentials from the Auth Action step automatically.

### Observed behavior

The Deploy to App Engine action fail because there are not credentials to do that.

![Screenshot_20211213_185708](https://user-images.githubusercontent.com/40150522/145907938-320703bb-3a6c-409f-b11c-cc779b39b9d3.png)

### Action YAML

```yaml
- id: 'auth'
  uses: 'google-github-actions/auth@v0.4.0'
  with:
    credentials_json: ${{ secrets.GCP_SA_KEY }}
        
- name: Deploy
  uses: google-github-actions/deploy-appengine@v0.4.0
  with:
    project_id: ${{ secrets.project_id }}
```
