### ISSUE TITLE
Non-descriptive gcloud error

### ISSUE THREAD

**Issue by gnuskidder69** [google-github-actions/deploy-appengine#197]
Question
I'm receiving the following error:

```
Run google-github-actions/deploy-appengine@v0.5.0
/usr/bin/tar xz -C /Users/runner/work/_temp/XXXXXXXXXXXXXXXX -f /Users/runner/work/_temp/XXXXXXXXXXXXXXXX
Error: google-github-actions/deploy-appengine failed with: The process '/Users/runner/hostedtoolcache/gcloud/368.0.0/x64/bin/gcloud' failed with exit code 1
```

The project was recently moved to a new repository and started failing. I'm guessing it's failing when attempting to run:
`gcloud app deploy --quiet app.yaml --promote`

I did observe different versions of github runners between repos:

Working
Current runner version: '2.285.1'

Not Working
Current runner version: '2.286.0'

action config file:
```
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy to Google App Engine
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm run test:generate-output
      - run: npm run build-storybook

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SECRET }}'

      - id: 'deploy'
        uses: google-github-actions/deploy-appengine@v0.5.0
        with:
          project_id: '${{ secrets.PROJECT_ID }}'

      - name: 'show output'
        run: 'echo ${{ steps.deploy.outputs.url }}'
```
        
gae app config
```
runtime: nodejs16
service: storybook-ui
handlers:
  - url: /
    static_files: storybook-static/index.html
    upload: storybook-static/index.html

  - url: /(.*)
    static_files: storybook-static/\1
    upload: storybook-static/(.*)
```

Any assistance in debugging this would be greatly appreciated! Thank you
