### ISSUE TITLE
Setting the directory to deploy

### ISSUE THREAD

**Issue by DeveloperRic** [google-github-actions/deploy-appengine#20]
### Question

How can I set the directory path to deploy from? I attempted using this action and it automatically uploaded thousands of dev files to my staging bucket. I only want to deploy files in my `/dist/app` directory.

In the Cloud Shell, in short, what I do is:
```shell
[src/app/frontend]: ls; ls www
app.yml www/
index.html main.js ....
[src/app/frontend]: gcloud app deploy
< Uploads files >
< my app.yml routes requests to serve files in www/ >
```

I want to replicate this in my CI workflow. At the moment this is what I have:

```yml
- name: Deploy test app to GAE ✈
  uses: google-github-actions/deploy-appengine@v0.2.0
  with:
  credentials: ${{ secrets.GCP_SA_KEY }}
  deliverables: './app-test.yml'
```

However, my build step (which runs before this) compiles files to `./dist/app`. How can I cd of the action?

P.s. I know I can do some renames and copies to get the directory structure in `./dist/app` to match that in my Cloud Shell. However, I don't know how to _use_ that directory.

**Comment by DeveloperRic** [comment]
Update: I've found a workaround by using [`google-github-actions/setup-gcloud`](https://github.com/marketplace/actions/set-up-gcloud-cloud-sdk-environment) and `gcloud app deploy`
```yaml
      - name: Build app for prod 🛠💻
        run: |
          npx ng build --prod
          mkdir -p bin/deployment
          cp -r app.yaml dist/eggx-external/ bin/deployment/
          cd bin/deployment
          mv eggx-external/ www/
          echo "Build ready for deployment at $(pwd)"
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy app to GAE 🚀
        run: |
          cd bin/deployment
          gcloud app deploy app.yaml
```
It would be nice though to just use this one action and configure it to deploy my `dist/` or `bin/deployment/` directory.

**Comment by averikitsch** [comment]
The `setup-gcloud` does give more flexibility. You can set the source via the deliverables input:
```
- name: Deploy test app to GAE ✈
  uses: google-github-actions/deploy-appengine@v0.2.0
  with:
      credentials: ${{ secrets.GCP_SA_KEY }}
      deliverables: 'bin/deployments/app-test.yml'
```
This will use the `bin/deployments` directory as the source. There will be a new input added to set the `working-directory` of the action (issue #10 ), which may also help here.
