### ISSUE TITLE
The process '/opt/hostedtoolcache/gcloud/370.0.0/x64/bin/gcloud' failed with exit code 1

### ISSUE THREAD

**Issue by archita-desai** [google-github-actions/deploy-appengine#215]
### TL;DR

This is the first time we are receiving this error for all our pipelines and projects.

While running google-github-actions/deploy-appengine@main in CI/CD, we are getting following error:

```
Error: google-github-actions/deploy-appengine failed with: The process '/opt/hostedtoolcache/gcloud/370.0.0/x64/bin/gcloud' failed with exit code 1
```

### Expected behavior

We expected for deployment to run successfully

### Observed behavior

The following error occurred:

```
Error: google-github-actions/deploy-appengine failed with: The process '/opt/hostedtoolcache/gcloud/370.0.0/x64/bin/gcloud' failed with exit code 1
```

### Action YAML

```yaml
name: Staging Deployment
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: npm ci
      - run: npm run build
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.DEPLOYMENT_ACCOUNT }}
          deliverables: staging-app.yaml
```

**Comment by sethvargo** [comment]
Hi @archita-desai 

Thank you for opening an issue. I believe we fixed this bug but have not released a new version yet. Could you please _temporarily_ try using `google-github-actions/deploy-appengine@main` to see if that resolves the issue? If not, can you please share the output from running `@main`? If it does fix your issue, we plan on releasing a new version this week.

**Comment by archita-desai** [comment]
Hi @sethvargo  we are already running `google-github-actions/deploy-appengine@main` for our deployments.

**Comment by archita-desai** [comment]
Hi @sethvargo,
We are already running google-github-actions/deploy-appengine@main for our deployments.

**Comment by archita-desai** [comment]
Hi @sethvargo,
As you can see in the Action YAML file shared above, we are always running deployment using `google-github-actions/deploy-appengine@main` and still we are receiving the error shared above.

We have been running with this mode of pipeline and Action YAML for quite a few months and never faced such an issue.

**Comment by sethvargo** [comment]
Hi @archita-desai 

Are you able to share the _full_ log output?

**Comment by archita-desai** [comment]
@sethvargo  please provide your email address so that I can share the log output file with you as it is confidential.

**Comment by archita-desai** [comment]
@sethvargo  some points from what I have observed from logs and debugging:

1. Inside deploy-app-engine.ts file, the logs can be seen till line 157: `logInfo(`Running: ${commandString}`);`
2. It seems that code is failing somewhere on line 160 inside deploy-app-engine.ts file and hence going inside the catch block.
3. Please note, when trying to run `gcloud app deploy dev-app.yaml` command locally on the terminal, the build gets deployed as expected.

**Comment by sethvargo** [comment]
Hi @archita-desai it look like you found my email. In reviewing the logs, I see some inconsistencies with the Action YAML you shared. Specifically, I see `##[group]Run google-github-actions/auth@v0` which is not in your Action YAML. Can you please share your complete Action YAML?

The issue here is that GitHub Actions is swallowing the output from our `gcloud` command. I've submitted #216 which, once merged, should make it so we see the complete error output that gcloud is providing.

**Comment by archita-desai** [comment]
@sethvargo  yes, just tried the same combination as here and found email.

Since we were receiving deprecation warning of passing auth variables, I had tried the newer way of passing credentials to see if it resolves the error. However, the error still persisted.
Hence, with both Action YAMLs, we are receiving the same error.

Here is the action YAML with `google-github-actions/auth@v0`:

```
name: Manual Branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Enter branch to deploy"
        required: true
        default: "staging"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: npm ci
      - run: npm run build
      - id: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEPLOYMENT_ACCOUNT }}
      - id: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: dev-app.yaml

```

Hope this helps.
