### ISSUE TITLE
Support env vars

### ISSUE THREAD

**Issue by maxwell-oroark** [google-github-actions/deploy-appengine#24]
### TL;DR

Could we please support adding environment variables to the deploy? These could be templated into app.yaml or something. Maybe expose the api like:

```
steps:
- id: deploy
  uses: google-github-actions/deploy-appengine@main
  with:
    credentials: ${{ secrets.gcp_credentials }}
    env_vars:
        envVarName: ${{ secrets.envVarName }}
    
```
  

### Design

**Action YAML**

```yaml
# Paste your proposed GitHub Actions YAML here.
```

**Resources**

- [Link to documentation](TODO)

**Additional information**

**Comment by gmile** [comment]
This would be so useful! At the moment, forced to do a dance like this:

```yaml
name: CD workflow

on:
  push:
    branches: app-engine

jobs:
  deploy_to_google_cloud:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - id: output-env-vars-to-file
      env:
        MY_DOTENV: ${{ secrets.MY_DOTENV }}
      run: echo "$MY_DOTENV" > .env-for-app-yaml

    - id: prepare-app-yaml
      uses: mshick/fast-envsubst@v1
      with:
        env-file: .env-for-app-yaml
        in-file: app.yaml.template
        out-file: app.yaml

    - id: actual-deploy-to-gae
      # ...
```

**Comment by flashadvocate** [comment]
> This would be so useful! At the moment, forced to do a dance like this:
> 
> ```yaml
> name: CD workflow
> 
> on:
>   push:
>     branches: app-engine
> 
> jobs:
>   deploy_to_google_cloud:
>     runs-on: ubuntu-20.04
> 
>     steps:
>     - uses: actions/checkout@v2
> 
>     - id: generate_dotenv_file
>       env:
>         MY_DOTENV: ${{ secrets.MY_DOTENV }}
>       run: echo "$MY_DOTENV" > .env-for-app-yaml
> 
>     - id: prepare-app-yaml
>       uses: mshick/fast-envsubst@v1
>       with:
>         env-file: .env-for-app-yaml
>         in-file: app.yaml.template
>         out-file: app.yaml
> 
>     - id: actual-deploy-to-gae
>       # ...
> ```



> This would be so useful! At the moment, forced to do a dance like this:
> 
> ```yaml
> name: CD workflow
> 
> on:
>   push:
>     branches: app-engine
> 
> jobs:
>   deploy_to_google_cloud:
>     runs-on: ubuntu-20.04
> 
>     steps:
>     - uses: actions/checkout@v2
> 
>     - id: generate_dotenv_file
>       env:
>         MY_DOTENV: ${{ secrets.MY_DOTENV }}
>       run: echo "$MY_DOTENV" > .env-for-app-yaml
> 
>     - id: prepare-app-yaml
>       uses: mshick/fast-envsubst@v1
>       with:
>         env-file: .env-for-app-yaml
>         in-file: app.yaml.template
>         out-file: app.yaml
> 
>     - id: actual-deploy-to-gae
>       # ...
> ```

Following your lead on this approach, can you explain what your process is here? I get that you're leveraging your `.env` to build an appropriate app.yaml, but not sure what the template ought to look like

**Comment by oskarhane** [comment]
This would be very useful, yes.

**Comment by iddan** [comment]
My current script for handling that:
```typescript
/**
 * Replace the environment variables values in app.yaml that match the $NAME
 * with the corresponding environment variable with the name NAME
 */

import * as fs from "fs";
import * as path from "path";

const APP_YAML_PATH = path.join(__dirname, "..", "app.yaml");

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

async function main() {
  const contents = await fs.promises.readFile(APP_YAML_PATH, "utf-8");
  const missingVariables: string[] = [];
  const updated = contents.replace(/\$[A-Z0-9_]+\b/g, (match) => {
    // Remove the leading dollar sign
    const name = match.substring(1);
    const value = process.env[name];
    if (typeof value !== "string") {
      missingVariables.push(name);
      return match;
    }
    return value;
  });
  if (missingVariables.length) {
    throw new Error(
      `The variables: ${missingVariables.join(", ")} are not defined in the environment`
    );
  }
  await fs.promises.writeFile(APP_YAML_PATH, updated);
}
```

Where the app.yaml file looks like:
```yaml
env_variables:
  # $ variables are expected to be replaced by environment variables
  FOO: $FOO
```

And call to the script looks like:
```yaml
     - name: Prepare environment variables
        run: yarn app-engine:replace-env-vars
        env:
          FOO: value
```
