### ISSUE TITLE
Cannot deploy due to `no key could be detected` gcloud error

### ISSUE THREAD

**Issue by leesus** [google-github-actions/deploy-appengine#250]
### TL;DR

I am unable to deploy to app engine. I am authenticating with credentials JSON, and a creds file is successfully created in the auth step, but the deployment fails with the error `gcloud crashed (ValueError): No key could be detected.`.

### Expected behavior

I expect my deployments to go through.

### Observed behavior

Passing through the service account key to gcloud appears to be failing.

### Action YAML

```yaml
name: Deploy master branch to GAE

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Verify build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts
      - name: Typecheck
        run: npm run typecheck
      - name: Test
        run: npm run test

  deploy:
    name: Deploy to app engine
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ***

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install --ignore-scripts
      - name: Authenticate with google
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_PRODUCTION }}
      - name: Deploy app
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml
      - name: Build for sentry
        run: npm run build
      - name: Create sentry release
        uses: getsentry/action-release@v1
        with:
          environment: 'production'
          sourcemaps: './build'
          version: ${{ github.sha }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ***
          SENTRY_PROJECT: ***
```

### Log output

```text
Run google-github-actions/auth@v0
  with:
    credentials_json: ***
    create_credentials_file: true
    export_environment_variables: true
    cleanup_credentials: true
    access_token_lifetime: 3600s
    access_token_scopes: https://www.googleapis.com/auth/cloud-platform
    id_token_include_email: false
Created credentials file at "/home/runner/work/***/***/gha-creds-5213d5b77770af71.json"

Run google-github-actions/deploy-appengine@v0
  with:
    deliverables: app.yaml
    promote: true
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/***/***/gha-creds-5213d5b77770af71.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/***/***/gha-creds-5213d5b77770af71.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/***/***/gha-creds-5213d5b77770af71.json
    CLOUDSDK_CORE_PROJECT: ***
    CLOUDSDK_PROJECT: ***
    GCLOUD_PROJECT: ***
    GCP_PROJECT: ***
    GOOGLE_CLOUD_PROJECT: ***

/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/7d8fd15a-300a-403a-b648-1a9959fa2f65 -f /home/runner/work/_temp/0667d982-ce1d-422e-9388-3c332b63e24b
Error: google-github-actions/deploy-appengine failed with: failed to execute command `gcloud --quiet auth activate-service-account *** --key-file -`: ERROR: gcloud crashed (ValueError): No key could be detected.
```

### Additional information

I've tried with both v0.8.0 and v0, neither works.
