### ISSUE TITLE
Issues with npm and deploy

### ISSUE THREAD

**Issue by REPTILEHAUS** [google-github-actions/deploy-appengine#299]
### TL;DR

Trying to deploy everything seems to go fine but then during deploy it complains about packages, however build happens before deploy step, no idea why its building again while deploying 

### Expected behavior

build successfully and deploy

### Observed behavior

builds successfully, tries to deploy but fails because of build errors

### Action YAML

```yaml
name: 'Staging'

on:
  push:
    branches:
    - 'staging'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'
    
    strategy:
      matrix:
        node-version: [18.13.0]    
    steps:  
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}   
    - run: npm config set legacy-peer-deps=true
    - run: npm install -f
    - run: npm run build:staging 
      working-directory: admin             

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'xyz'
        service_account: 'xyz'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'admin/app.yaml'
        project_id: 'staging-project'
        promote: true

    - name: 'show output'
      run: 'echo ${{ steps.deploy.outputs.url }}'
      
    - id: remove
      name: 'Remove old versions'    
      uses: Reviewable/appengine-remove-action@v2.1.2
      with:
        limit: 1     
        
    # Example of using the output
    - id: test
      name: 'Remove old versions OUTPUTS'       
      run: |
        echo "${{ steps.remove.outputs.versions_deleted }}"
        echo "${{ steps.remove.total_deleted }}"
```

### Log output

```text
target service account:      [App Engine default service account]


Beginning deployment of service [default]...
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 1 file to Google Cloud Storage                 ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
Updating service [default]...
........................................................................................................................................................failed.
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx status: FAILURE
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @agm/core@1.1.0
npm ERR! Found: @angular/common@12.2.17
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.2.17" from the root project
npm ERR!   peer @angular/common@">=6.1.0" from @angular-slider/ngx-slider@2.0.4
npm ERR!   node_modules/@angular-slider/ngx-slider
npm ERR!     @angular-slider/ngx-slider@"^2.0.4" from the root project
npm ERR!   19 more (@angular/forms, @angular/platform-browser, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^6.0.0 || ^7.0.0 || ^8.0.0" from @agm/core@1.1.0
npm ERR! node_modules/@agm/core
npm ERR!   @agm/core@"^1.0.0" from the root project
npm ERR!   peer @agm/core@"^1.0.0-beta.7" from @agm/snazzy-info-window@1.1.0
npm ERR!   node_modules/@agm/snazzy-info-window
npm ERR!     @agm/snazzy-info-window@"^1.0.0" from the root project
npm ERR!
```
