### ISSUE TITLE
Version 1.2 throws with "could not find 'app.yml' file"

### ISSUE THREAD

**Issue by nwaughachukwuma** [google-github-actions/deploy-appengine#303]
### TL;DR

The new version 1.2 fails with the following error.

```bash
Error: google-github-actions/deploy-appengine failed with: could not find "app.yml" file
```

### Expected behavior

Deployment should succeed without error with other things remaining the same.

### Observed behavior

Deployment fails with the following error.

```bash
Error: google-github-actions/deploy-appengine failed with: could not find "app.yml" file
```

### Action YAML

```yaml
on:
  workflow_call:
    inputs:
      PROJECT:
        required: true
        type: string
      VERSION:
        required: true
        type: string
      PROMOTE:
        required: false
        type: string
        default: 'false'
      CONFIG_FILE:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string
      NOT_RENOVATE:
        required: true
        type: string
      HEALTH_CHECK_PATH:
        required: false
        default: ''
        type: string
      BASE_PATH:
        required: false
        default: ''
        type: string
      SERVICE:
        required: true
        type: string
      PING_WARMUP:
        required: false
        default: false
        type: boolean
      WORKING_DIRECTORY:
        required: true
        type: string
    secrets:
      SERVICE_ACCOUNT_KEY:
        required: true

jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.PROJECT }}
          path: ${{ inputs.WORKING_DIRECTORY }}
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
      - id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          project_id: ${{ inputs.PROJECT_ID }}
          deliverables: ${{ inputs.CONFIG_FILE }}
          promote: ${{ inputs.PROMOTE }}
          version: ${{ inputs.VERSION }}
          working_directory: ${{ inputs.WORKING_DIRECTORY }}
      - name: health check
        run: curl -f "${{ steps.deploy.outputs.version_url }}${{ inputs.BASE_PATH }}${{ inputs.HEALTH_CHECK_PATH }}"
      - name: warmup
        if: ${{ inputs.PING_WARMUP }}
        run: curl -f "${{ steps.deploy.outputs.version_url }}/_ah/warmup"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ inputs.PROJECT }}
          message: |
            ${{ inputs.PROJECT }}: ${{ steps.deploy.outputs.version_url }}${{ inputs.BASE_PATH }} (${{ github.event.pull_request.head.sha }})
```

### Log output

```text
Changing into working directory: src/apps/admin-app
Error: google-github-actions/deploy-appengine failed with: could not find "app.yml" file
```

### Additional information

Reverting to v1.1.0 fixed the issue.

**Comment by clintonb** [comment]
Source of the problem: https://github.com/google-github-actions/deploy-appengine/compare/v1.1.0...v1.2.0#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR289

**Comment by sethvargo** [comment]
Duplicate of https://github.com/google-github-actions/deploy-appengine/issues/302, fix is in https://github.com/google-github-actions/deploy-appengine/pull/305.

**Comment by sethvargo** [comment]
Actually wait - this is a slightly different error.

**Comment by sethvargo** [comment]
How are you deploying without an app.yaml deliverable?

**Comment by clintonb** [comment]
Our files are named `app-dev.yaml` and `app-prod.yaml`. 

```yaml
- id: deploy-dev
  name: 'Deploy dev services'
  uses: google-github-actions/deploy-appengine@v1
  with:
    promote: true
    deliverables: services/flex-worker/app-dev.yaml
    flags: '--stop-previous-version'
  env: 
    CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1200
```
