### ISSUE TITLE
Unable to use env_vars

### ISSUE THREAD

**Issue by satvikreddy** [google-github-actions/deploy-appengine#315]
### TL;DR

When passing `env_vars` in github action config, i get an error: google-github-actions/deploy-appengine failed with: could not find an appyaml in [backend/app.yaml]

The moment i remove `env_vars`, deployment passes.

### Expected behavior

App engine deployment should pass when using env_vars

### Observed behavior

App engine deployment works without env_vars, but fails when using env_vars

### Action YAML

```yaml
name: Deploy to staging CI
on:
  push:
    branches:
      - staging

jobs:
  build_deploy_app_engine:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: backend
      - name: Build
        run: npm run build
        working-directory: backend
      - name: "GCloud Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
      - name: Deploy
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: vahanchal--staging
          deliverables: backend/app.yaml
          env_vars: |-
            DATABASE_URL=${{ secrets.DATABASE_URL_STAGING }}
            SLACK_ERROR_CHANNEL_WEBHOOK=${{ secrets.SLACK_ERROR_CHANNEL_WEBHOOK_STAGING }}
```

### Log output

```text
2023-03-28T19:20:12.5424328Z ##[error]google-github-actions/deploy-appengine failed with: could not find an appyaml in [backend/app.yaml]
2023-03-28T19:20:12.5498993Z Post job cleanup.
```

### Additional information

My app.yaml config:
I've also tried without specifying `env_variables` in app.yaml still no luck

```
runtime: nodejs18

env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

env_variables:
  DATABASE_URL: ""
  SLACK_ERROR_CHANNEL_WEBHOOK: ""
```
