### ISSUE TITLE
How to Deploy a specific branch? - not the master/main branch.

### ISSUE THREAD

**Issue by martinandersen3d** [google-github-actions/deploy-appengine#33]
### Question

I'm not shure if this is possible or I have misunderstood something.

I would like to have multiple branches like this:
* Main/Master branch, that deploys to **"Server1_production"**
* Staging branch, called "Staging" or "Beta" branch, that deploys to **"Server2_beta"**

Do I have to specify the branch name to deploy? Can i specify the branch name that I want to deploy? If so, how?

Does it only work with master/main branch?

Thanks

```

name: Node.js DEPLOY

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  Deploy_Google_App_Engine:
    name: Deploy To Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_PLATFORM_CREDENTIALS }}

```

**Comment by averikitsch** [comment]
Hi @martinandersen3d, you can achieve this by [specifying the trigger type and branch](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags). There are a few ways to do this. But the main idea is specifying which branch will trigger the workflow.

You could set up 2 different workflow files:
```YAML
on:
  push:
    branches: [ main ]
jobs:
  Deploy_Google_App_Engine:
    name: Deploy To Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_PLATFORM_CREDENTIALS }}
          version: server1_prod 
          # Or you could specify project_id if deploying to a different GCP project or deliverable and specify a different app.yaml ie app.prod.yaml
```
```YAML
on:
  push:
    branches: [ staging ]
jobs:
  Deploy_Google_App_Engine:
    name: Deploy To Google App Engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_PLATFORM_CREDENTIALS }}
          version: server2_beta 
```

Or you could set up one workflow file and for every push to the branch (or merged PR into the branch) 'main' and 'staging' would start this workflow:
```YAML
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
      # Push events to branches matching refs/heads/staging
      - staging
```
However, you would need [expressions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions) to specify where you are deploying.
```YAML
jobs:
  prod:
    name: Deploy To Google App Engine
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_PLATFORM_CREDENTIALS }}
          version: server1_prod
          # Or you could specify project_id if deploying to a different GCP project or deliverable and specify a different app.yaml ie app.prod.yaml

  staging:
    name: Deploy To Google App Engine
    if: ${{ github.ref == 'refs/heads/staging' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploying to staging server on branch $GITHUB_REF"
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_PLATFORM_CREDENTIALS }}
          version: server2_beta
```
There are other ways to use conditionals if you don't want to specify the job twice.
