### ISSUE TITLE
The component [app-engine-go] not being installed

### ISSUE THREAD

**Issue by dantonio1401** [google-github-actions/deploy-appengine#332]
### TL;DR

For whatever reason my pipeline is no longer deploying to app engine with the error ```The component [app-engine-go] is required for staging this application``` What's also strange is that it is actually running:
```
┌───────────────────────────────────────────────────┐
│        These components will be installed.        │
├──────────────────────────────┬─────────┬──────────┤
│             Name             │ Version │   Size   │
├──────────────────────────────┼─────────┼──────────┤
│ App Engine Go Extensions     │  1.9.75 │  4.5 MiB │
│ Cloud Datastore Emulator     │   2.3.1 │ 36.2 MiB │
│ gRPC Python library          │  1.20.0 │  2.1 MiB │
│ gcloud app Python Extensions │ 1.9.105 │  8.5 MiB │
└──────────────────────────────┴─────────┴──────────┘

For the latest full release notes, please visit:
  https://cloud.google.com/sdk/release_notes

╔════════════════════════════════════════════════════════════╗
╠═ Creating update staging area                             ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Installing: App Engine Go Extensions                     ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Installing: App Engine Go Extensions                     ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Installing: Cloud Datastore Emulator                     ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Installing: gRPC Python library                          ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Installing: gRPC Python library                          ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Installing: gcloud app Python Extensions                 ═╣
╚════════════════════════════════════════════════════════════╝
╔════════════════════════════════════════════════════════════╗
╠═ Creating backup and activating new installation          ═╣
╚════════════════════════════════════════════════════════════╝
```

which I thought would install the component but it is not. Has anyone else run into this issue? This happened seemingly over night

### Action YAML

```yaml
- name: App Engine Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: App Engine Deployment
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: go/src/github.com/myapp/app-dev.yaml go/src/github.com/myapp/cron.yaml
        env:
          GO111MODULE: off
```
```


### Log output

_No response_

### Additional information

_No response_
