### ISSUE TITLE
Build in successful in the GCP build Logs for App Engine but GitHub Actions fails later with pnpm

### ISSUE THREAD

**Issue by geekysaurabh001** [google-github-actions/deploy-appengine#345]
### TL;DR

```
Error: google-github-actions/deploy-appengine failed with: failed to execute gcloud command `gcloud app deploy --quiet --format json pnpm-app.yaml --project *** --promote`: Services to deploy:

descriptor:                  [/home/runner/work/***-co.in/***-co.in/pnpm-app.yaml]
source:                      [/home/runner/work/***-co.in/***-co.in]
target project:              [***]
target service:              some_service
target version:              some_version
target url:                  some_url
target service account:      some_service_account


Beginning deployment of service [some_service]...
Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 4 files to Google Cloud Storage                ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
Updating service [some_service]...
```

After this, it fails.

### Expected behavior

If the build is successful, the deployment should happen.

### Observed behavior

The deployment doesn't happen with pnpm. npm isn't tested as legacy dependencies are present and I cannot change the npm ci command of the gcp app engine during the whole process unlike the control over gcp-build command. yarn works for some reason.

### Action YAML

```yaml
name: PNPM Test Deployment
on:
  push:
    branches:
      - 'new_branch'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.STAGING_DEPLOYMENT_SERVICE_ACCOUNT }}'
      - id: Deploy
        uses: google-github-actions/deploy-appengine@v2
        env:
          CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800
        with:
          project_id: ''
          deliverables: pnpm-app.yaml
          build_env_vars: |-
            __all environment key-value are listed here__
```

### Additional information

pnpm-yaml file

```
env: standard
runtime: nodejs20
service: new_service
instance_class: F2

handlers:
  - url: /.*
    secure: always
    script: auto
    redirect_http_response_code: 301
```
