### ISSUE TITLE
Deploy to app Engine : Authentication backend unknown error

### ISSUE THREAD

**Issue by jhadraoui** [google-github-actions/deploy-appengine#359]
### TL;DR

I'm trying to continuously deploy a project from Github to Google appengine using github actions, but it results in a 500 error and I do not understand why. 

### Expected behavior

Deploy to google engine after checkout and authentication 

### Observed behavior

Checkout and authentication steps  are successful. 
Deploy to App Engine step failed with error 500 : "Authentication backend unknown error."
Works perfectly when deploying directly from host without using Github actions 

### Action YAML

```yaml
name: Deploying app to App Engine

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      # checkout the latest codebase using actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: "id_of_my_gproject"
          workload_identity_provider: 'projects/123456781100/locations/global/workloadIdentityPools/github/providers/repo'
        
        # Deploying the latest version of code using deploy-appengine Github Action
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2.1.0
        with:
          project_id: "id_of_my_gproject"
```

### Log output

```text
Run google-github-actions/deploy-appengine@v2.1.0
Successfully authenticated
Running: gcloud app deploy --quiet --format json app.yaml --project id_of_my_gproject --promote
Error: google-github-actions/deploy-appengine failed with: failed to execute gcloud command `gcloud app deploy --quiet --format json app.yaml --project id_of_my_gproject--promote`: ERROR: (gcloud.app.deploy) HttpError accessing <https://appengine.googleapis.com/v1/apps/id_of_my_gproject?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 08 Apr 2024 23:30:29 GMT', 'server': 'ESF', 'cache-control': 'private', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': '500', 'content-length': '118', '-content-encoding': 'gzip'}>, content <{
  "error": {
    "code": 500,
    "message": "Authentication backend unknown error.",
    "status": "UNKNOWN"
  }
}
>
This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.
```
