### ISSUE TITLE
Gcloud Crashed Multierror

### ISSUE THREAD

**Issue by alisahinozcelik** [google-github-actions/deploy-appengine#378]
### TL;DR

```
ERROR: gcloud crashed (MultiError): One or more errors occurred:
MaxRe
```
this is all the message thrown. 

### Expected behavior

Eighter the full error message is shown or it works properly

### Observed behavior

The error message is cut in half and action doesn't work

### Action YAML

```yaml
name: Tentacles / Publish

on:
  release:
    types: [created]

jobs:
  publish:
    if: startsWith(github.ref_name, 'tentacles-v')
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      TAG_NAME: ${{github.ref_name}}

    steps:
      - name: Set package version env variable
        run: echo "PACKAGE_VERSION=${TAG_NAME#tentacles-v}" | sed 's/\./-/g' >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - id: 'gc-auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GC_APPENGINE_SA_JSON }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v2'
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}
          deliverables: './apps/tentacles/app.yaml'
          version: ${{ env.PACKAGE_VERSION }}
```

### Log output

```text
Run google-github-actions/deploy-appengine@v2
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/bc3d51da-2129-4dec-96a9-64ca8cf22a89 -f /home/runner/work/_temp/f8e048da-cd8a-46fa-b814-da7cd4455b87
Successfully authenticated
Running: gcloud app deploy --format json ./apps/tentacles/app.yaml --project *** --version 1-0-7 --promote
Error: google-github-actions/deploy-appengine failed with: failed to execute gcloud command `gcloud app deploy --format json ./apps/tentacles/app.yaml --project *** --version 1-0-7 --promote`: Services to deploy:

descriptor:                  [/home/runner/work/***/***/apps/tentacles/app.yaml]
source:                      [/home/runner/work/***/***/apps/tentacles]
target project:              [***]
target service:              [tentacles]
target version:              [1-0-7]
target url:                  [https://tentacles-dot-***.lm.r.appspot.com]
target service account:      [***@appspot.gserviceaccount.com]


Beginning deployment of service [tentacles]...
Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 38 files to Google Cloud Storage               ═╣
╚════════════════════════════════════════════════════════════╝
ERROR: gcloud crashed (MultiError): One or more errors occurred:
MaxRe
```
